# 1-1. 명시적 예외처리

## ✏️  명시적 예외처리

```java
try { /* 예외 발생의 가능성이 있는 코드 */ }
catch( /* 예외 타입 */ ) { /* 예외가 발생한 경우 수행될 코드 */ }
finally { /* 예외발생 여부와 상관 없이 수행될 코드 */ }
```

```java
try {
	System.out.println(str[i++]);
}catch(NullPointerException e){
	System.out.println("Nice Catch / 1.NullPointerException");
}**catch(ArrayIndexOutOfBoundsException e){
	System.out.println("Nice Catch / 2.ArrayIndexOutOfBoundsException");
}**finally{
	System.out.println("Finally");
}
```

- `try` 에는 예외 발생의 가능성이 있는 코드를 입력하며, 예외 발생이 되지 않는 경우 수행된다
- `catch` 에는 예외 타입 참조 변수를 인자로 갖으며, 예외가 발생했을 때 수행될 코드를 작성한다
    - JVM은 버그가 발생하면 발생한 예외 타입으로 객체를 생성한다. 생성된 객체를  catch문의 인자로 받아온다
    - catch문은 인자값의 예외 타입을 다르게 하여 여러개 작성할 수 있다.
    - catch문은 자식 → 부모 순으로 작성해야한다 / 그렇지 않으면 여러개의 catch문이 실행될 수 있기 때문이다
    - 여러개의 catch문 중, JVM이 전달한 예외 타입과 동일한 인자를 가진 catch문 하나만이 실행된다
    - 만약 예외타입과 동일한 인자를 가지는 catch문이 없다면 프로그램은 비정상 종료하게 된다
    - catch문에는 예외에 대한 설명을 출력하는 `e.printStackTrace()` , `e.getMessage()` 를 사용하기도 한다
        - `e.printStackTrace()` 는 자체적으로 출력해주는 메서드
        - `e.getMessage()` 는 자체적으로 출력하지 못하므로 sysout안에서 출력해주어야한다
- `finally` 에는 예외 발생 여부와 상관없이 무조건 수행될 코드를 작성한다
    - 자원의 누수를 막는 코드를 일반적으로 finally문에 작성한다